# Site settings
title: Dislabeled Philly Film Series 
email: david@townsendclark.com
description: > # this means to ignore newlines until "baseurl:"
  Website for the upcoming Dislabeled Philly Film Series
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dislabeledphilly.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  davidtnc

# Build settings
markdown: kramdown
